"""Parsing XML that came from somebody else.

Two of this toolkit's inputs are documents other people produced: a collaborator's
manuscript, and a checklist downloaded from a guideline site. Both are zip archives of XML,
and both were being handed straight to `xml.etree.ElementTree` with no limits.

That is exploitable, and not theoretically. A four-level entity bomb in `word/document.xml`
expands to 30,000 characters under this parser; ten levels is gigabytes from a file of a few
hundred bytes. A zip member also decompresses fully into memory with no cap, so a small
archive can carry an enormous part.

The fix here is deliberately not a new dependency. `defusedxml` would work, but the specific
hole has a precise shape: **a legitimate OOXML part never contains a document type
declaration**, so refusing any part that has one closes entity expansion completely, in
three lines, with nothing to install. Size caps close the rest.
"""

from __future__ import annotations

import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

# A Word or Excel part is generated by an office suite and never carries a DTD. Anything
# that does is either corrupt or trying something.
_DOCTYPE = re.compile(rb"<!\s*(?:DOCTYPE|ENTITY)\b", re.IGNORECASE)

MAX_ARCHIVE_BYTES = 80 * 1024 * 1024
MAX_PART_BYTES = 120 * 1024 * 1024
MAX_RATIO = 200  # decompressed:compressed, past which a member is a bomb rather than prose


class UnsafeDocument(Exception):
    """The document is malformed, implausibly large, or contains a DTD."""


def parse_xml(data: bytes, *, what: str = "XML") -> ET.Element:
    """Parse XML that is not trusted. Raises UnsafeDocument rather than expanding a bomb."""
    if len(data) > MAX_PART_BYTES:
        raise UnsafeDocument(
            f"{what} is {len(data) // 1024 // 1024} MB, past the {MAX_PART_BYTES // 1024 // 1024} "
            f"MB limit; refusing to parse it"
        )
    if _DOCTYPE.search(data[:8192]):
        raise UnsafeDocument(
            f"{what} declares a DTD or an entity. Office documents never do, and entity "
            f"expansion is how a small file becomes gigabytes. Refusing to parse it."
        )
    try:
        return ET.fromstring(data)
    except ET.ParseError as exc:
        raise UnsafeDocument(f"{what} is malformed: {exc}") from exc


def open_archive(path: Path) -> zipfile.ZipFile:
    """Open a zip, refusing one that is too large or whose members inflate implausibly."""
    try:
        size = path.stat().st_size
    except OSError as exc:
        raise UnsafeDocument(f"{path.name}: cannot stat ({exc})") from exc
    if size > MAX_ARCHIVE_BYTES:
        raise UnsafeDocument(
            f"{path.name} is {size // 1024 // 1024} MB; a manuscript or checklist is not"
        )
    try:
        archive = zipfile.ZipFile(path)
    except (zipfile.BadZipFile, OSError) as exc:
        raise UnsafeDocument(f"{path.name}: not a readable archive ({exc})") from exc

    for info in archive.infolist():
        if info.file_size > MAX_PART_BYTES:
            raise UnsafeDocument(
                f"{path.name}: member {info.filename} expands to "
                f"{info.file_size // 1024 // 1024} MB"
            )
        if info.compress_size and info.file_size / info.compress_size > MAX_RATIO:
            raise UnsafeDocument(
                f"{path.name}: member {info.filename} inflates "
                f"{info.file_size // max(info.compress_size, 1)}x, which is a compression "
                f"bomb rather than a document"
            )
    return archive


def read_part(archive: zipfile.ZipFile, name: str, *, what: str | None = None) -> ET.Element:
    """Read one archive member and parse it safely."""
    try:
        data = archive.read(name)
    except (KeyError, zipfile.BadZipFile, OSError) as exc:
        raise UnsafeDocument(f"cannot read {name} ({exc})") from exc
    return parse_xml(data, what=what or name)
